### ISSUE TITLE
[Demo] рефакторинг адаптивности

### ISSUE THREAD

**Issue by in19farkt** [fullstack-development/react-redux-starter-kit#78]
Адаптив нужно строить по принципу mobile first. Для удобства нужно написать миксины, синтаксис должен быть примерно такой:

```scss
.block {
  width: 100%;

  @include breakpoint-up(sm) {
    width: 10rem;
  }

  @include breakpoint-up(md) {
    width: 14rem;
  }
}
```
